spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/angat_buhat_db
    username: admin
    password: password
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update